server:
  port: 10010
spring:
  thymeleaf:
    cache: false
    #配置druid连接池
  datasource:
    url: jdbc:mysql://localhost:3306/guns?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: qaz.456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    #配置日志
logging:
  #指定不同目录下的日志的级别
  level:
    com.stylefeng.shiro.controller: debug
  config: classpath:logback-spring.xml
  #此处存放日志的路径
  path: D:\后端java进阶中级篇\项目

mybatis:
  type-aliases-package: com.stylefeng.shiro.admin
  mapper-locations: classpath:mapper/*.xml
